// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	domain0 "github.com/mocoarow/cocotola-1.24/cocotola-core/domain"
	"github.com/mocoarow/cocotola-1.24/moonbeam/user/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCardQueryUsecase creates a new instance of MockCardQueryUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCardQueryUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCardQueryUsecase {
	mock := &MockCardQueryUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCardQueryUsecase is an autogenerated mock type for the CardQueryUsecase type
type MockCardQueryUsecase struct {
	mock.Mock
}

type MockCardQueryUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCardQueryUsecase) EXPECT() *MockCardQueryUsecase_Expecter {
	return &MockCardQueryUsecase_Expecter{mock: &_m.Mock}
}

// FindCardsByDeckID provides a mock function for the type MockCardQueryUsecase
func (_mock *MockCardQueryUsecase) FindCardsByDeckID(ctx context.Context, operator domain.UserInterface, deckID *domain0.DeckID) ([]*domain0.CardModel, error) {
	ret := _mock.Called(ctx, operator, deckID)

	if len(ret) == 0 {
		panic("no return value specified for FindCardsByDeckID")
	}

	var r0 []*domain0.CardModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface, *domain0.DeckID) ([]*domain0.CardModel, error)); ok {
		return returnFunc(ctx, operator, deckID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface, *domain0.DeckID) []*domain0.CardModel); ok {
		r0 = returnFunc(ctx, operator, deckID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain0.CardModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserInterface, *domain0.DeckID) error); ok {
		r1 = returnFunc(ctx, operator, deckID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCardQueryUsecase_FindCardsByDeckID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindCardsByDeckID'
type MockCardQueryUsecase_FindCardsByDeckID_Call struct {
	*mock.Call
}

// FindCardsByDeckID is a helper method to define mock.On call
//   - ctx
//   - operator
//   - deckID
func (_e *MockCardQueryUsecase_Expecter) FindCardsByDeckID(ctx interface{}, operator interface{}, deckID interface{}) *MockCardQueryUsecase_FindCardsByDeckID_Call {
	return &MockCardQueryUsecase_FindCardsByDeckID_Call{Call: _e.mock.On("FindCardsByDeckID", ctx, operator, deckID)}
}

func (_c *MockCardQueryUsecase_FindCardsByDeckID_Call) Run(run func(ctx context.Context, operator domain.UserInterface, deckID *domain0.DeckID)) *MockCardQueryUsecase_FindCardsByDeckID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserInterface), args[2].(*domain0.DeckID))
	})
	return _c
}

func (_c *MockCardQueryUsecase_FindCardsByDeckID_Call) Return(cardModels []*domain0.CardModel, err error) *MockCardQueryUsecase_FindCardsByDeckID_Call {
	_c.Call.Return(cardModels, err)
	return _c
}

func (_c *MockCardQueryUsecase_FindCardsByDeckID_Call) RunAndReturn(run func(ctx context.Context, operator domain.UserInterface, deckID *domain0.DeckID) ([]*domain0.CardModel, error)) *MockCardQueryUsecase_FindCardsByDeckID_Call {
	_c.Call.Return(run)
	return _c
}
