// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/mocoarow/cocotola-1.24/cocotola-core/domain"

	mock "github.com/stretchr/testify/mock"

	service "github.com/mocoarow/cocotola-1.24/cocotola-core/service"
)

// WorkbookCommandUsecase is an autogenerated mock type for the WorkbookCommandUsecase type
type WorkbookCommandUsecase struct {
	mock.Mock
}

type WorkbookCommandUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *WorkbookCommandUsecase) EXPECT() *WorkbookCommandUsecase_Expecter {
	return &WorkbookCommandUsecase_Expecter{mock: &_m.Mock}
}

// AddWorkbook provides a mock function with given fields: ctx, operator, param
func (_m *WorkbookCommandUsecase) AddWorkbook(ctx context.Context, operator service.OperatorInterface, param *service.WorkbookAddParameter) (*domain.WorkbookID, error) {
	ret := _m.Called(ctx, operator, param)

	if len(ret) == 0 {
		panic("no return value specified for AddWorkbook")
	}

	var r0 *domain.WorkbookID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.OperatorInterface, *service.WorkbookAddParameter) (*domain.WorkbookID, error)); ok {
		return rf(ctx, operator, param)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.OperatorInterface, *service.WorkbookAddParameter) *domain.WorkbookID); ok {
		r0 = rf(ctx, operator, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.WorkbookID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.OperatorInterface, *service.WorkbookAddParameter) error); ok {
		r1 = rf(ctx, operator, param)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WorkbookCommandUsecase_AddWorkbook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddWorkbook'
type WorkbookCommandUsecase_AddWorkbook_Call struct {
	*mock.Call
}

// AddWorkbook is a helper method to define mock.On call
//   - ctx context.Context
//   - operator service.OperatorInterface
//   - param *service.WorkbookAddParameter
func (_e *WorkbookCommandUsecase_Expecter) AddWorkbook(ctx interface{}, operator interface{}, param interface{}) *WorkbookCommandUsecase_AddWorkbook_Call {
	return &WorkbookCommandUsecase_AddWorkbook_Call{Call: _e.mock.On("AddWorkbook", ctx, operator, param)}
}

func (_c *WorkbookCommandUsecase_AddWorkbook_Call) Run(run func(ctx context.Context, operator service.OperatorInterface, param *service.WorkbookAddParameter)) *WorkbookCommandUsecase_AddWorkbook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(service.OperatorInterface), args[2].(*service.WorkbookAddParameter))
	})
	return _c
}

func (_c *WorkbookCommandUsecase_AddWorkbook_Call) Return(_a0 *domain.WorkbookID, _a1 error) *WorkbookCommandUsecase_AddWorkbook_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WorkbookCommandUsecase_AddWorkbook_Call) RunAndReturn(run func(context.Context, service.OperatorInterface, *service.WorkbookAddParameter) (*domain.WorkbookID, error)) *WorkbookCommandUsecase_AddWorkbook_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWorkbook provides a mock function with given fields: ctx, operator, workbookID, version, param
func (_m *WorkbookCommandUsecase) UpdateWorkbook(ctx context.Context, operator service.OperatorInterface, workbookID *domain.WorkbookID, version int, param *service.WorkbookUpdateParameter) error {
	ret := _m.Called(ctx, operator, workbookID, version, param)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWorkbook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, service.OperatorInterface, *domain.WorkbookID, int, *service.WorkbookUpdateParameter) error); ok {
		r0 = rf(ctx, operator, workbookID, version, param)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WorkbookCommandUsecase_UpdateWorkbook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWorkbook'
type WorkbookCommandUsecase_UpdateWorkbook_Call struct {
	*mock.Call
}

// UpdateWorkbook is a helper method to define mock.On call
//   - ctx context.Context
//   - operator service.OperatorInterface
//   - workbookID *domain.WorkbookID
//   - version int
//   - param *service.WorkbookUpdateParameter
func (_e *WorkbookCommandUsecase_Expecter) UpdateWorkbook(ctx interface{}, operator interface{}, workbookID interface{}, version interface{}, param interface{}) *WorkbookCommandUsecase_UpdateWorkbook_Call {
	return &WorkbookCommandUsecase_UpdateWorkbook_Call{Call: _e.mock.On("UpdateWorkbook", ctx, operator, workbookID, version, param)}
}

func (_c *WorkbookCommandUsecase_UpdateWorkbook_Call) Run(run func(ctx context.Context, operator service.OperatorInterface, workbookID *domain.WorkbookID, version int, param *service.WorkbookUpdateParameter)) *WorkbookCommandUsecase_UpdateWorkbook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(service.OperatorInterface), args[2].(*domain.WorkbookID), args[3].(int), args[4].(*service.WorkbookUpdateParameter))
	})
	return _c
}

func (_c *WorkbookCommandUsecase_UpdateWorkbook_Call) Return(_a0 error) *WorkbookCommandUsecase_UpdateWorkbook_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WorkbookCommandUsecase_UpdateWorkbook_Call) RunAndReturn(run func(context.Context, service.OperatorInterface, *domain.WorkbookID, int, *service.WorkbookUpdateParameter) error) *WorkbookCommandUsecase_UpdateWorkbook_Call {
	_c.Call.Return(run)
	return _c
}

// NewWorkbookCommandUsecase creates a new instance of WorkbookCommandUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkbookCommandUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkbookCommandUsecase {
	mock := &WorkbookCommandUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
