load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "gin",
    srcs = ["app_router.go"],
    importpath = "github.com/mocoarow/cocotola-1.24/cocotola-auth/controller/gin",
    visibility = ["//visibility:public"],
    deps = [
        "//cocotola-auth/config",
        "//cocotola-auth/controller/gin/middleware",
        "//cocotola-auth/controller/gin/private",
        "//cocotola-auth/controller/gin/public",
        "//cocotola-auth/gateway",
        "//cocotola-auth/service",
        "//cocotola-auth/usecase",
        "//lib/controller/gin",
        "//lib/domain",
        "//moonbeam/lib/errors",
        "//moonbeam/user/service",
        "@com_github_gin_gonic_gin//:gin",
        "@com_github_golang_jwt_jwt_v5//:jwt",
        "@io_opentelemetry_go_contrib_instrumentation_net_http_otelhttp//:otelhttp",
    ],
)