---
version: "2"
run:
  go: "1.24"
  build-tags:
    - small
    - medium
    - large
linters:
  enable:
    - bodyclose
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - gocognit
    - gocyclo
    - gosec
    - noctx
    - testpackage
    - thelper
    - unconvert
    - whitespace
    - asasalint
    - dupword
    - dupl
    - exptostd
    - nestif
    - goconst
    - tagliatelle
    - nlreturn
    - predeclared
    - importas
    - revive
    - goheader
    - nolintlint
    - paralleltest
    - testifylint
    - spancheck
    - staticcheck
    - wrapcheck
    - forcetypeassert
    - canonicalheader
    - decorder
    - nilnil
    - prealloc
    - mirror
    - misspell
    - nilerr
    - noctx
    - predeclared
    - reassign
    - unconvert
    - gocheckcompilerdirectives
    - makezero
    - exhaustruct
    - exhaustive
    - fatcontext

  settings:
    forbidigo:
      forbid:
        - pattern: ^fmt\.Print.*$
    gocognit:
      min-complexity: 20
    gocyclo:
      min-complexity: 10
    gosec:
      excludes:
        - G115
    staticcheck:
      checks:
        - all
    wrapcheck:
      extra-ignore-sigs:
        - errors.Errorf(
        - .Errorf(
        - .Errorf
        - liberrors.Errorf(
      ignore-sigs:
        - errors.Errorf(
        - .Errorf(
        - .Errorf
        - errors.New(
        - liberrors.Errorf(
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - lib/gateway/sqlite/db_sqlite3_migrate.go
      - third_party$
      - builtin$
      - examples$
    rules:
      # Exclude some linters from running on tests files.
      - path: _test\.go
        linters:
          - dupl
          - nlreturn
          - revive
          - exhaustruct
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - lib/gateway/sqlite/db_sqlite3_migrate.go
      - third_party$
      - builtin$
      - examples$
