sonar.projectKey=mocoarow_cocotola-1.24
sonar.organization=mocoarow


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=cocotola-1.24
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-
sonar.go.lcov.reportPaths=coverage.lcov
