// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	domain0 "github.com/mocoarow/cocotola-1.24/cocotola-core/domain"
	"github.com/mocoarow/cocotola-1.24/cocotola-core/service"
	"github.com/mocoarow/cocotola-1.24/moonbeam/user/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDeckRepository creates a new instance of MockDeckRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeckRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeckRepository {
	mock := &MockDeckRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeckRepository is an autogenerated mock type for the DeckRepository type
type MockDeckRepository struct {
	mock.Mock
}

type MockDeckRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeckRepository) EXPECT() *MockDeckRepository_Expecter {
	return &MockDeckRepository_Expecter{mock: &_m.Mock}
}

// AddDeck provides a mock function for the type MockDeckRepository
func (_mock *MockDeckRepository) AddDeck(ctx context.Context, operator domain.UserInterface, param *service.AddDeckParameter) (*domain0.DeckID, error) {
	ret := _mock.Called(ctx, operator, param)

	if len(ret) == 0 {
		panic("no return value specified for AddDeck")
	}

	var r0 *domain0.DeckID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface, *service.AddDeckParameter) (*domain0.DeckID, error)); ok {
		return returnFunc(ctx, operator, param)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface, *service.AddDeckParameter) *domain0.DeckID); ok {
		r0 = returnFunc(ctx, operator, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain0.DeckID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserInterface, *service.AddDeckParameter) error); ok {
		r1 = returnFunc(ctx, operator, param)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeckRepository_AddDeck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddDeck'
type MockDeckRepository_AddDeck_Call struct {
	*mock.Call
}

// AddDeck is a helper method to define mock.On call
//   - ctx
//   - operator
//   - param
func (_e *MockDeckRepository_Expecter) AddDeck(ctx interface{}, operator interface{}, param interface{}) *MockDeckRepository_AddDeck_Call {
	return &MockDeckRepository_AddDeck_Call{Call: _e.mock.On("AddDeck", ctx, operator, param)}
}

func (_c *MockDeckRepository_AddDeck_Call) Run(run func(ctx context.Context, operator domain.UserInterface, param *service.AddDeckParameter)) *MockDeckRepository_AddDeck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserInterface), args[2].(*service.AddDeckParameter))
	})
	return _c
}

func (_c *MockDeckRepository_AddDeck_Call) Return(deckID *domain0.DeckID, err error) *MockDeckRepository_AddDeck_Call {
	_c.Call.Return(deckID, err)
	return _c
}

func (_c *MockDeckRepository_AddDeck_Call) RunAndReturn(run func(ctx context.Context, operator domain.UserInterface, param *service.AddDeckParameter) (*domain0.DeckID, error)) *MockDeckRepository_AddDeck_Call {
	_c.Call.Return(run)
	return _c
}

// FindDecks provides a mock function for the type MockDeckRepository
func (_mock *MockDeckRepository) FindDecks(ctx context.Context, operator domain.UserInterface, param *service.FindDecksParameter) ([]*domain0.Deck, error) {
	ret := _mock.Called(ctx, operator, param)

	if len(ret) == 0 {
		panic("no return value specified for FindDecks")
	}

	var r0 []*domain0.Deck
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface, *service.FindDecksParameter) ([]*domain0.Deck, error)); ok {
		return returnFunc(ctx, operator, param)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface, *service.FindDecksParameter) []*domain0.Deck); ok {
		r0 = returnFunc(ctx, operator, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain0.Deck)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserInterface, *service.FindDecksParameter) error); ok {
		r1 = returnFunc(ctx, operator, param)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeckRepository_FindDecks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindDecks'
type MockDeckRepository_FindDecks_Call struct {
	*mock.Call
}

// FindDecks is a helper method to define mock.On call
//   - ctx
//   - operator
//   - param
func (_e *MockDeckRepository_Expecter) FindDecks(ctx interface{}, operator interface{}, param interface{}) *MockDeckRepository_FindDecks_Call {
	return &MockDeckRepository_FindDecks_Call{Call: _e.mock.On("FindDecks", ctx, operator, param)}
}

func (_c *MockDeckRepository_FindDecks_Call) Run(run func(ctx context.Context, operator domain.UserInterface, param *service.FindDecksParameter)) *MockDeckRepository_FindDecks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserInterface), args[2].(*service.FindDecksParameter))
	})
	return _c
}

func (_c *MockDeckRepository_FindDecks_Call) Return(decks []*domain0.Deck, err error) *MockDeckRepository_FindDecks_Call {
	_c.Call.Return(decks, err)
	return _c
}

func (_c *MockDeckRepository_FindDecks_Call) RunAndReturn(run func(ctx context.Context, operator domain.UserInterface, param *service.FindDecksParameter) ([]*domain0.Deck, error)) *MockDeckRepository_FindDecks_Call {
	_c.Call.Return(run)
	return _c
}

// FindDecksByOwner provides a mock function for the type MockDeckRepository
func (_mock *MockDeckRepository) FindDecksByOwner(ctx context.Context, operator domain.UserInterface) ([]*domain0.Deck, error) {
	ret := _mock.Called(ctx, operator)

	if len(ret) == 0 {
		panic("no return value specified for FindDecksByOwner")
	}

	var r0 []*domain0.Deck
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface) ([]*domain0.Deck, error)); ok {
		return returnFunc(ctx, operator)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface) []*domain0.Deck); ok {
		r0 = returnFunc(ctx, operator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain0.Deck)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserInterface) error); ok {
		r1 = returnFunc(ctx, operator)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeckRepository_FindDecksByOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindDecksByOwner'
type MockDeckRepository_FindDecksByOwner_Call struct {
	*mock.Call
}

// FindDecksByOwner is a helper method to define mock.On call
//   - ctx
//   - operator
func (_e *MockDeckRepository_Expecter) FindDecksByOwner(ctx interface{}, operator interface{}) *MockDeckRepository_FindDecksByOwner_Call {
	return &MockDeckRepository_FindDecksByOwner_Call{Call: _e.mock.On("FindDecksByOwner", ctx, operator)}
}

func (_c *MockDeckRepository_FindDecksByOwner_Call) Run(run func(ctx context.Context, operator domain.UserInterface)) *MockDeckRepository_FindDecksByOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserInterface))
	})
	return _c
}

func (_c *MockDeckRepository_FindDecksByOwner_Call) Return(decks []*domain0.Deck, err error) *MockDeckRepository_FindDecksByOwner_Call {
	_c.Call.Return(decks, err)
	return _c
}

func (_c *MockDeckRepository_FindDecksByOwner_Call) RunAndReturn(run func(ctx context.Context, operator domain.UserInterface) ([]*domain0.Deck, error)) *MockDeckRepository_FindDecksByOwner_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveDeckByID provides a mock function for the type MockDeckRepository
func (_mock *MockDeckRepository) RetrieveDeckByID(ctx context.Context, operator domain.UserInterface, deckID *domain0.DeckID) (*domain0.Deck, error) {
	ret := _mock.Called(ctx, operator, deckID)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveDeckByID")
	}

	var r0 *domain0.Deck
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface, *domain0.DeckID) (*domain0.Deck, error)); ok {
		return returnFunc(ctx, operator, deckID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface, *domain0.DeckID) *domain0.Deck); ok {
		r0 = returnFunc(ctx, operator, deckID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain0.Deck)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserInterface, *domain0.DeckID) error); ok {
		r1 = returnFunc(ctx, operator, deckID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeckRepository_RetrieveDeckByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveDeckByID'
type MockDeckRepository_RetrieveDeckByID_Call struct {
	*mock.Call
}

// RetrieveDeckByID is a helper method to define mock.On call
//   - ctx
//   - operator
//   - deckID
func (_e *MockDeckRepository_Expecter) RetrieveDeckByID(ctx interface{}, operator interface{}, deckID interface{}) *MockDeckRepository_RetrieveDeckByID_Call {
	return &MockDeckRepository_RetrieveDeckByID_Call{Call: _e.mock.On("RetrieveDeckByID", ctx, operator, deckID)}
}

func (_c *MockDeckRepository_RetrieveDeckByID_Call) Run(run func(ctx context.Context, operator domain.UserInterface, deckID *domain0.DeckID)) *MockDeckRepository_RetrieveDeckByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserInterface), args[2].(*domain0.DeckID))
	})
	return _c
}

func (_c *MockDeckRepository_RetrieveDeckByID_Call) Return(deck *domain0.Deck, err error) *MockDeckRepository_RetrieveDeckByID_Call {
	_c.Call.Return(deck, err)
	return _c
}

func (_c *MockDeckRepository_RetrieveDeckByID_Call) RunAndReturn(run func(ctx context.Context, operator domain.UserInterface, deckID *domain0.DeckID) (*domain0.Deck, error)) *MockDeckRepository_RetrieveDeckByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDeck provides a mock function for the type MockDeckRepository
func (_mock *MockDeckRepository) UpdateDeck(ctx context.Context, operator domain.UserInterface, deckID *domain0.DeckID, version int, param *service.UpdateDeckParameter) error {
	ret := _mock.Called(ctx, operator, deckID, version, param)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDeck")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface, *domain0.DeckID, int, *service.UpdateDeckParameter) error); ok {
		r0 = returnFunc(ctx, operator, deckID, version, param)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeckRepository_UpdateDeck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDeck'
type MockDeckRepository_UpdateDeck_Call struct {
	*mock.Call
}

// UpdateDeck is a helper method to define mock.On call
//   - ctx
//   - operator
//   - deckID
//   - version
//   - param
func (_e *MockDeckRepository_Expecter) UpdateDeck(ctx interface{}, operator interface{}, deckID interface{}, version interface{}, param interface{}) *MockDeckRepository_UpdateDeck_Call {
	return &MockDeckRepository_UpdateDeck_Call{Call: _e.mock.On("UpdateDeck", ctx, operator, deckID, version, param)}
}

func (_c *MockDeckRepository_UpdateDeck_Call) Run(run func(ctx context.Context, operator domain.UserInterface, deckID *domain0.DeckID, version int, param *service.UpdateDeckParameter)) *MockDeckRepository_UpdateDeck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserInterface), args[2].(*domain0.DeckID), args[3].(int), args[4].(*service.UpdateDeckParameter))
	})
	return _c
}

func (_c *MockDeckRepository_UpdateDeck_Call) Return(err error) *MockDeckRepository_UpdateDeck_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeckRepository_UpdateDeck_Call) RunAndReturn(run func(ctx context.Context, operator domain.UserInterface, deckID *domain0.DeckID, version int, param *service.UpdateDeckParameter) error) *MockDeckRepository_UpdateDeck_Call {
	_c.Call.Return(run)
	return _c
}
