load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "domain",
    srcs = [
        "errors.go",
        "guest.go",
        "init.go",
        "space.go",
        "strings.go",
        "system_token.go",
    ],
    importpath = "github.com/mocoarow/cocotola-1.24/lib/domain",
    visibility = ["//visibility:public"],
)
