load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "domain",
    srcs = [
        "deck.go",
        "init.go",
        "profile.go",
        "space.go",
        "template.go",
        "workbook.go",
    ],
    importpath = "github.com/mocoarow/cocotola-1.24/cocotola-core/domain",
    visibility = ["//visibility:public"],
    deps = [
        "//moonbeam/lib/domain",
        "//moonbeam/lib/errors",
        "//moonbeam/user/domain",
    ],
)

go_test(
    name = "domain_s_test",
    size = "small",
    srcs = ["deck_test.go"],
    gotags = ["small"],
    deps = [
        ":domain",
        "//moonbeam/lib/domain",
        "//moonbeam/user/domain",
        "@com_github_stretchr_testify//require",
    ],
)

go_test(
    name = "domain_test",
    srcs = ["deck_test.go"],
    deps = [
        ":domain",
        "//moonbeam/lib/domain",
        "//moonbeam/user/domain",
        "@com_github_stretchr_testify//require",
    ],
)
