load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "usecase",
    srcs = [
        "add_personal_space_command.go",
        "authentication_usecase.go",
        "callback_usecase.go",
        "func.go",
        "get_user_info_query.go",
        "google_user_usecase.go",
        "guest_authenticate_command.go",
        "guest_usecase.go",
        "password_authenticate_command.go",
        "password_usecase.go",
        "rbac_usecase.go",
        "register_user_command.go",
        "user_usecase.go",
    ],
    importpath = "github.com/mocoarow/cocotola-1.24/cocotola-auth/usecase",
    visibility = ["//visibility:public"],
    deps = [
        "//cocotola-auth/domain",
        "//cocotola-auth/service",
        "//lib/domain",
        "//lib/rbac",
        "//moonbeam/lib/errors",
        "//moonbeam/lib/log",
        "//moonbeam/lib/service",
        "//moonbeam/user/domain",
        "//moonbeam/user/service",
        "//moonbeam/user/usecase",
        "@com_github_golang_jwt_jwt_v5//:jwt",
    ],
)
