load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "public",
    srcs = [
        "auth_handler.go",
        "google_auth_handler.go",
        "guest_auth_handler.go",
        "password_auth_handler.go",
        "user_handler.go",
    ],
    importpath = "github.com/mocoarow/cocotola-1.24/cocotola-auth/controller/gin/public",
    visibility = ["//visibility:public"],
    deps = [
        "//cocotola-auth/controller/gin/helper",
        "//cocotola-auth/domain",
        "//lib/api/auth",
        "//lib/controller/gin",
        "//moonbeam/lib/domain",
        "//moonbeam/lib/log",
        "//moonbeam/user/domain",
        "//moonbeam/user/service",
        "@com_github_gin_gonic_gin//:gin",
    ],
)

go_test(
    name = "public_test",
    srcs = [
        "auth_handler_s_test.go",
        "google_auth_handler_s_test.go",
        "helper_test.go",
    ],
    deps = [
        ":public",
        "//cocotola-auth/config",
        "//cocotola-auth/controller/gin/public/mocks",
        "//cocotola-auth/domain",
        "//lib/config",
        "//lib/controller/gin",
        "//moonbeam/lib/config",
        "//moonbeam/user/domain",
        "@com_github_gin_gonic_gin//:gin",
        "@com_github_ohler55_ojg//jp",
        "@com_github_ohler55_ojg//oj",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//mock",
        "@com_github_stretchr_testify//require",
    ],
)

go_test(
    name = "public_s_test",
    size = "small",
    srcs = [
        "auth_handler_s_test.go",
        "google_auth_handler_s_test.go",
        "helper_test.go",
    ],
    gotags = ["small"],
    deps = [
        ":public",
        "//cocotola-auth/config",
        "//cocotola-auth/controller/gin/public/mocks",
        "//cocotola-auth/domain",
        "//lib/config",
        "//lib/controller/gin",
        "//moonbeam/lib/config",
        "//moonbeam/user/domain",
        "@com_github_gin_gonic_gin//:gin",
        "@com_github_ohler55_ojg//jp",
        "@com_github_ohler55_ojg//oj",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//mock",
        "@com_github_stretchr_testify//require",
    ],
)
