load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "api",
    srcs = ["deck.go"],
    importpath = "github.com/mocoarow/cocotola-1.24/cocotola-core/api",
    visibility = ["//visibility:public"],
    deps = [
        "//cocotola-core/domain",
        "//lib/api/moonbeam",
    ],
)

go_test(
    name = "api_test",
    srcs = ["deck_handler_test.go"],
    deps = [
        ":api",
        "//cocotola-core/domain",
        "//lib/api/moonbeam",
        "//moonbeam/lib/domain",
        "//moonbeam/user/domain",
    ],
)
