load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "gin",
    srcs = [
        "app_router.go",
        "callback_handler.go",
        "card_handler.go",
        "deck_handler.go",
        "helper.go",
        "init.go",
        "profile_handler.go",
    ],
    importpath = "github.com/mocoarow/cocotola-1.24/cocotola-core/controller/gin",
    visibility = ["//visibility:public"],
    deps = [
        "//cocotola-auth/domain",
        "//cocotola-core/config",
        "//cocotola-core/controller/gin/helper",
        "//cocotola-core/controller/gin/middleware",
        "//cocotola-core/domain",
        "//cocotola-core/gateway/guest",
        "//cocotola-core/gateway/resource_manager",
        "//cocotola-core/service",
        "//cocotola-core/usecase",
        "//cocotola-core/usecase/resource_manager",
        "//lib/api",
        "//lib/api/core",
        "//lib/controller/gin",
        "//lib/domain",
        "//lib/gateway",
        "//moonbeam/lib/domain",
        "//moonbeam/lib/errors",
        "//moonbeam/lib/log",
        "//moonbeam/user/domain",
        "//moonbeam/user/service",
        "@com_github_gin_gonic_gin//:gin",
        "@io_gorm_gorm//:gorm",
        "@io_opentelemetry_go_contrib_instrumentation_net_http_otelhttp//:otelhttp",
        "@io_opentelemetry_go_otel//:otel",
    ],
)

go_test(
    name = "gin_test",
    srcs = ["helper_test.go"],
)
