load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "usecase",
    srcs = [
        "callback_on_add_user_space_command.go",
        "callback_usecase.go",
        "get_my_profile_query.go",
        "init.go",
        "profile_usecase.go",
    ],
    importpath = "github.com/mocoarow/cocotola-1.24/cocotola-core/usecase",
    visibility = ["//visibility:public"],
    deps = [
        "//cocotola-core/domain",
        "//cocotola-core/service",
        "//lib/api",
        "//moonbeam/lib/errors",
        "//moonbeam/lib/log",
        "//moonbeam/lib/service",
        "//moonbeam/user/domain",
        "@io_opentelemetry_go_otel//:otel",
    ],
)
