---
name: Build
on:
  push:
    tags:
      - "*"
  workflow_dispatch:
# permissions: read-all
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.24.x]
    runs-on: ubuntu-latest
    permissions:
      # kics-scan ignore-line
      id-token: write
    steps:
      - uses: actions/checkout@v4

      # test
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APPS_APP_ID }}
          private-key: ${{ secrets.APPS_PRIVATE_KEY }}
          owner: mocoarow

      # This step needs 'id-token: write' permission
      # Error: google-github-actions/auth failed with: gitHub Actions did not inject $ACTIONS_ID_TOKEN_REQUEST_TOKEN or $ACTIONS_ID_TOKEN_REQUEST_URL into this job.
      # This most likely means the GitHub Actions workflow permissions are incorrect, or this job is being run from a fork.
      # For more information, please see https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.REGISTRY_SERVICE_ACCOUNT_EMAIL }}

      - uses: google-github-actions/setup-gcloud@v2

      # - run: ls -la ${GOOGLE_GHA_CREDS_PATH}

      # - run: gcloud info

      # - run: ls -la ${GOOGLE_GHA_CREDS_PATH}

      # - run: echo ${{ github.ref_name}}

      - run: gcloud artifacts repositories describe --location us-west1 cocotola-synthesizer

      # - uses: bazelbuild/setup-bazelisk@v2
      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-version: 1.x

      # - name: Mount bazel cache
      #   id: bazel_cache
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.cache/bazel
      #     key: bazel

      # - name: Check cache
      #   run: echo "cache=${{ steps.bazel_cache.outputs.cache-hit }}"

      - run: bazel info

      - uses: arduino/setup-task@v2

      # - run: ls -la ${GOOGLE_GHA_CREDS_PATH}

      - run: task build

      - run: gcloud auth configure-docker us-west1-docker.pkg.dev --quiet

      - run: TAG=${{ github.ref_name }} task push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-image:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      # kics-scan ignore-line
      id-token: write
    steps:
      - uses: actions/checkout@v4

      # This step needs 'id-token: write' permission
      # Error: google-github-actions/auth failed with: gitHub Actions did not inject $ACTIONS_ID_TOKEN_REQUEST_TOKEN or $ACTIONS_ID_TOKEN_REQUEST_URL into this job.
      # This most likely means the GitHub Actions workflow permissions are incorrect, or this job is being run from a fork.
      # For more information, please see https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.REGISTRY_SERVICE_ACCOUNT_EMAIL }}

      - uses: google-github-actions/setup-gcloud@v2

      # - id: digest_synthesizer
      #   run: |
      #     DIGEST=$(gcloud artifacts docker tags list us-west1-docker.pkg.dev/mocoarow-25-08/cocotola-synthesizer/cocotola-synthesizer --format json | jq -r '.[] |  select(.tag=="projects/mocoarow-25-08/locations/us-west1/repositories/cocotola-synthesizer/packages/cocotola-synthesizer/tags/latest") | .version' | cut -d':' -f 2)
      #     echo "digest=$DIGEST" >> "$GITHUB_OUTPUT"

      # - run: echo ${{ steps.digest_synthesizer.outputs.digest }}

      # - run: cat ./.github/workflows/update-image.json
      # - run: |
      #     jq '.inputs += {"synthesizer": "${{ steps.digest_synthesizer.outputs.digest }}"}' ./.github/workflows/update-image.json  > ./.github/workflows/update-image.json.tmp
      #     mv ./.github/workflows/update-image.json.tmp ./.github/workflows/update-image.json

      - run: cat ./.github/workflows/update-image.json

      - id: digest_empty
        run: |
          DIGEST=$(gcloud artifacts docker tags list us-west1-docker.pkg.dev/mocoarow-25-08/cocotola-empty/cocotola-empty --format json | jq -r '.[] |  select(.tag=="projects/mocoarow-25-08/locations/us-west1/repositories/cocotola-empty/packages/cocotola-empty/tags/latest") | .version' | cut -d':' -f 2)
          echo "digest=$DIGEST" >> "$GITHUB_OUTPUT"

      - run: echo ${{ steps.digest_empty.outputs.digest }}

      - id: digest_app
        run: |
          DIGEST=$(gcloud artifacts docker tags list us-west1-docker.pkg.dev/mocoarow-25-08/cocotola-app/cocotola-app --format json | jq -r '.[] |  select(.tag=="projects/mocoarow-25-08/locations/us-west1/repositories/cocotola-app/packages/cocotola-app/tags/latest") | .version' | cut -d':' -f 2)
          echo "digest=$DIGEST" >> "$GITHUB_OUTPUT"

      - run: echo ${{ steps.digest_app.outputs.digest }}

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APPS_APP_ID }}
          private-key: ${{ secrets.APPS_PRIVATE_KEY }}
          owner: mocoarow

      - run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ steps.app-token.outputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/mocoarow/google-mocoarow-25-08-terraform/actions/workflows/update-image.yml/dispatches \
          -d '{ "ref": "main", "inputs": { "app": "${{ steps.digest_app.outputs.digest }}", "empty": "${{ steps.digest_empty.outputs.digest }}" } }'
