---
name: Test KICS action PR comment
on:
  pull_request:
# permissions: read-all
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: run kics Scan
        uses: checkmarx/kics-github-action@v2.1.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ./
          config_path: .github/kics.yml
          output_path: kick_results/
