load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "guest",
    srcs = [
        "card_usecase.go",
        "deck_usecase.go",
        "init.go",
    ],
    importpath = "github.com/mocoarow/cocotola-1.24/cocotola-core/usecase/guest",
    visibility = ["//visibility:public"],
    deps = [
        "//cocotola-core/domain",
        "//cocotola-core/service",
        "//lib/api",
        "//lib/api/auth",
        "//lib/rbac",
        "//moonbeam/lib/errors",
        "//moonbeam/lib/log",
        "//moonbeam/user/domain",
        "@io_opentelemetry_go_otel//:otel",
    ],
)
